# Additional values file to decorate kafka with extra-cluster listeners.
kafka:
  auth:
    externalClientProtocol: tls
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer

postgresql:
  primary:
    service:
      type: LoadBalancer
