apiVersion: v1
kind: Service
metadata:
  name: {{ include "corda-dev.postgresName" . | quote }}
  labels:
    {{- include "corda-dev.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  selector:
    {{- include "corda-dev.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "postgres"
  ports:
    - protocol: "TCP"
      port: 5432
      targetPort: 5432
      name: "postgres"