apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "corda-dev.postgresName" . | quote }}
  labels:
    {{- include "corda-dev.labels" . | nindent 4 }}
data:
  {{- tpl (.Files.Glob "postgres-config/*").AsConfig . | nindent 2 }}