apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "corda-dev.postgresName" . | quote }}
  labels:
    {{- include "corda-dev.labels" . | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "500M"