apiVersion: v1
kind: Service
metadata:
  name: {{ include "corda-dev.kafkaName" . | quote }}
  labels:
    {{- include "corda-dev.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "corda-dev.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: kafka