apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "corda-dev-prereqs.kafkaName" . | quote }}
  labels:
    {{- include "corda-dev-prereqs.labels" . | nindent 4 }}
data:
  {{- tpl (.Files.Glob "kafka-config/*").AsConfig . | nindent 2 }}