apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "corda-dev-prereqs.kafkaName" . | quote }}
  labels:
    {{- include "corda-dev-prereqs.labels" . | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "500M"
  storageClassName: {{ .Values.storageClassName }}