apiVersion: v2
name: corda-dev
description: A Helm chart for installing Corda 5 development pre-requisites

type: application
version: 0.1.0
appVersion: "5.0.0"

dependencies:
  - name: postgresql
    version: 11.1.28
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: kafka
    version: 16.2.10
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
