# values for configuring bitnami/kafka sub-chart.
kafka:
  # -- enable/disable kafka.
  enabled: true
  # Configuring Kafka image.
  image:
    tag: 3.6.1-debian-11-r0
  # -- Extra env vars to pass to the kafka containers.
  extraEnvVars:
    - name: ALLOW_PLAINTEXT_LISTENER
      value: "yes"
  # -- set a static replica count of kafka brokers.
  replicaCount: 1
  # -- enable/disable auto-creation of topics.
  autoCreateTopicsEnable: false
  # listeners config.
  listeners:
    # client listener config.
    client:
      # -- protocol of the client listener.
      protocol: SASL_SSL
    # interbroker listener config.
    interbroker:
      # -- protocol of the inter broker listener used for replication.
      protocol: SSL
  # SASL configuration.
  sasl:
    # -- sasl mechanism e.g. scram-sha-256.
    mechanism: "scram-sha-256"
    # client configuration.
    client:
      # -- client users to authenticate with Kafka.
      users:
        - "user"
      # -- client passwords to authenticate with Kafka; generated if not specified.
      passwords:
  # tls configuration.
  tls:
    # -- type of the tls certificates.
    type: PEM
    # -- autogenerate a CA, and signed certificates for each broker.
    autoGenerated: true
  # -- the authorizer to use for access control
  authorizerClassName: "kafka.security.authorizer.AclAuthorizer"
  # values configuring KRaft.
  kraft:
    # -- enable/disable KRaft.
    enabled: true
    # -- set a static replica count of zookeeper nodes.
    replicaCount: 1

# values for configuring bitnami/postgres sub-chart.
postgresql:
  # -- enable/disable postgres.
  enabled: true
  # Configuring PostgreSQL image.
  image:
    tag: 16.1.0-debian-11-r19
  # values configuring the permissions of volumes.
  volumePermissions:
    # -- enable/disable an init container which changes ownership of the mounted volumes.
    enabled: true
  # Configuring TLS.
  tls:
    # -- enable TLS for postgres. 
    enabled: true
    # -- enable automatic certificate generation for postgres.
    autoGenerated: true
  # auth configuration.
  auth:
    # -- name of database to be created.
    database: cordacluster
    # -- name of the user to be created.
    username: user
    # -- name of the password of the user to be created - defaults to generated value.
    password:
  # primary (read/write instance) configuration.
  primary:
    # Custom init configuration..
    initdb:
      # -- ConfigMap-like object containing scripts to be executed on startup.
      # @default -- corda_user_init.sh
      scripts:
        corda_user_init.sh: |
          export PGPASSFILE=/tmp/pgpasswd$$
          touch $PGPASSFILE
          chmod 600 $PGPASSFILE
          trap "rm $PGPASSFILE" EXIT
          echo "localhost:${POSTGRES_PORT_NUMBER:-5432}:$POSTGRESQL_DATABASE:postgres:$POSTGRES_POSTGRES_PASSWORD" > $PGPASSFILE
          psql -v ON_ERROR_STOP=1 cordacluster <<-EOF
            ALTER ROLE "$POSTGRES_USER" NOSUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;
          EOF
